### ISSUE TITLE
Missing Code

### ISSUE THREAD

**Issue by navierula** [ryanlee8/intro-data-capstone-biodiversity#1]
Hi @ryanlee8! Thanks for submitting your pdf file, but in order for me to grade your assignment, I'll actually need to see and review the code as well since I am unable to access the learning environment. You can let me know when you've uploaded that here and I can get right to grading it!

**Comment by ryanlee8** [comment]
Hi @navierula ! Thanks for your note - I am unsure of how to upload my code, though. I thought since I completed the code on the Codecademy site that you would be able to access it? If not, please let me know how to give you access! Thank you!

**Comment by ryanlee8** [comment]
Hi @navierula - I just pasted all of the code into the readme.txt file. Can you please let me know if you are able to review it now? Thanks.

**Comment by navierula** [comment]
@ryanlee8 Since this is code, can you paste it into a Jupyter notebook or Python file and submit that here in this repository?

**Comment by ryanlee8** [comment]
@navierula I do not know how to paste it into a Python file and submit it here. Can you please provide instructions? This is my first time using this

**Comment by navierula** [comment]
1. Open a text editor
2. Copy and paste your code in there
3. Save your file with a .py extension
4. Upload it here

**Comment by ryanlee8** [comment]
[Ryan Lee - Codecademy Intro to DA.py.docx](https://github.com/ryanlee8/intro-data-capstone-biodiversity/files/2923707/Ryan.Lee.-.Codecademy.Intro.to.DA.py.docx)

**Comment by ryanlee8** [comment]
Please let me know if that works..

**Comment by navierula** [comment]
Hi @ryanlee8, I've been in touch with someone from support and I'll be able to grade your code in the previous format, so no worries. I'll have my report to you soon.

**Comment by ryanlee8** [comment]
Oh ok. Thank you.
