### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [ryanlee8/intro-data-capstone-biodiversity#2]
**Presentation / Analysis Document (4/4)**
All the requirements are met in the analysis document

**Code Accuracy (4/4)**
Accurate Python code for every question in the project for Matplotlib plots, Data analysis, and Hypothesis testing	

**Understanding hypothesis testing and interpreting the p-value (4/4)**
Stated the hypothesis, Ran hypothesis testing and stated the results, Interpreted the hypothesis outcome and connected to the objective of the analysis

**Objective and Recommendation / Conclusion meets the requirements (4/4)**
Objective clearly states the business reason for the analysis, Findings are interpreted accurately and are summarized in Recommendation / Conclusion

---

Overall, you did a great job with your project and you seem to really understand data analysis. Your presentation was also fun to go through. I would only recommend working to better understand code file structure, since it is important to save and upload files in formats that relate to the language you write in. Other than that, great job!

**Comment by ryanlee8** [comment]
@navierula Thank you very much for your review - appreciate the time spent doing that! Thanks also for the feedback. 
Best,
Ryan
